### ISSUE TITLE
90-epel.preset ?

### ISSUE THREAD

**Issue by retr0h** [goozbach-ansible/role-epel#5]
What is the rationale behind the 90-epel.preset file?  There are a lot of services being started that I would not want started on a production server.  For example cups and bluetooth.  Would you be opposed to conditionally installing this file?  The default behavior can be to install it, with the ability not to?

**Comment by retr0h** [comment]
Nevermind, I see there is an option for it.  Unfortunately, it is implemented as a hash, which means I must override the entire goozbach_epel_hash, due to the way ansible merges dicts.

**Comment by goozbach** [comment]
I've just copied the file as the epel-release package has it.
So I don't know why it is there exactly. 

The preset_enabled variable is to determine if it's needed in the version of RHEL/CENTOS as it only exists in EL7 IIRC.
